# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll-Photo-Gallery
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

owner:
  disqus-shortname: theowinterch
  name: Theodor Winter
  email: theo@w1nter.com
  googleplus: +TheoWinterCH
  github: aerobless
  twitter: TheodorWinter
  avatar: bio-photo.jpg # 160x160 px image for author byline

# Build settings
markdown: kramdown

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - images/photography #Set to location of photos

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: images/photography
        destination: images/photography/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "400x250"